# Generated by Django 5.1.2 on 2024-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioAlum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_completo', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioPro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_completo', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=59)),
            ],
        ),
    ]
